services:
  postgres:
    image: postgres:17
    container_name: questionnaire_db
    restart: always
    environment:
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: postgresSecret
      POSTGRES_DB: dynamic_questionnaire
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgresUser -d dynamic_questionnaire"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: questionnaire_backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5011:5011"
    environment:
      DATABASE_URL: postgresql://postgresUser:postgresSecret@postgres:5432/dynamic_questionnaire
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: >
      sh -c "
      npx prisma generate &&
      npx prisma migrate deploy &&
      npm run seed &&
      npm run dev
      "

  frontend:
    build: ./frontend
    container_name: questionnaire_frontend
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - backend

volumes:
  postgres_data:
